name = "mashedkeyboard"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-05-25"
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[[d1_databases]]
binding = "BLOGDB"
database_name = "blog"
database_id = "be9eb7fa-4fd2-4af1-acec-0620563c92f1"
preview_database_id = "24c938eb-3261-4527-936f-c9f9f80c0e21"